### ISSUE TITLE
Prompt to save when sending an open page for approval or publishing

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#1]
In v4.3, if you have a page open for editing in the console and click the "Send for approval" or "Send for publishing" buttons, there isn't a requirement to save the page beforehand.

An open page with pending changes probably shouldn't allow for sending unless all changes have been saved first. This would either mean hiding the send buttons prior to a save, or adding a confirmation dialogue to the send buttons with an option to save at that time.

I'm highlighting this because while reviewing Composite for use at our university, some testers were sending blank pages for approval because they hadn't saved them.

(Also logged on CodePlex)

**Comment by mawtex** [comment]
In v5 this should be less of an issue as you need to leave the "edit page" screen to access the mentioned buttons. If you experience there is still an issue with usability around these buttons in v5, please reopen this.

**Comment by DBailey635** [comment]
Thanks Marcus.
