### ISSUE TITLE
[5.0 Bug] Multiple functions on a page never stops loading

### ISSUE THREAD

**Issue by slacto** [Orckestra/C1-CMS#103]
Often one of the functions renders with function preview and sometimes without preview. Sometimes all functions keeps loading.
It is the same on both local and staging environment.

**Comment by wwwysocki** [comment]
This is a known unfortunate issue :(

* In some environments (like Microsoft Azure) it will load without preview. Previews just don't work.
* True, it might take some time to load a preview or load no preview, unfortunately.
* In some cases caching plays its role - in case of no preview. In this case, you may want to try to resize the content area - just moving the splitter left or right - the one that separates the content area from the template switcher area.

**Comment by wwwysocki** [comment]
@slacto Do you by any chance have steps for reproduction?

Thank you

**Comment by DBailey635** [comment]
Some JQuery functions can cause C1 function previews to never stop loading in PhantomJS (tabs and accordions are particularly problematic). @Napernik gave me some code to wrap the functions with to prevent this happening.

**Comment by DBailey635** [comment]
This was the code change he suggested:

```
$(document).ready(function () {
	// Tabs:
	$(".tabs").tabs({
		heightStyle: "content",
		show: { effect: "slideDown", duration: 1000 },
		hide: { effect: "slideUp", duration: 1000 }
	});
});
```

... became:

```
$(document).ready(function () {
	// Tabs:
	if ($('.tabs #CompositeC1FunctionPreview').length == 0) {
		$(".tabs").tabs({
			heightStyle: "content",
			show: { effect: "slideDown", duration: 1000 },
			hide: { effect: "slideUp", duration: 1000 }
		});
	};
})
```

**Comment by burningice2866** [comment]
Implementing https://github.com/Orckestra/C1-CMS/issues/78 would make it very easy to do a global switch for not rendering function previews on ie. platforms where its known not to work.

**Comment by napernik** [comment]
We've done some fixes/optimizations to the function previewing code, so starting from the next release it should be more stable/performant, as well as should there be any errors, you should be able to see them in C1 log files afterwards. 

Knows issues:
1. Doesn't work on Windows Azure Websites. Before it wouldn't work at all, now previews work, but no text content is rendered. Most likely related to GDI+ api that phantomjs uses.
2. in versions 5.0 and earlier, phantomjs wouldn't cache the css/js/image files, so have even a single http reference with a slow connection would cause every function preview on a page to hang.
3. Long running custom written javascript on a function (or a page template) may case to a timeout on phantomjs or change the output in unexpected way (like it was in @DBailey635 's case)
The way to address it, would be to look into the exact http link that PhantomJs renders, and check it with Chrome:
1) Open the preview image in a new tab (with help of Chome's Developer tools)
The url should look like:
http://<website name>/Renderers/FunctionBox?type=function&title=Geo+Related+Jumbotron&description=......
2) Change "FunctionBox" to "FunctionPreview.ashx" in the url:
http://<website name>/Renderers/FunctionPreview.ashx?type=function&title=Geo+Related+Jumbotron&description=......
3) With the help of Developer Tool, check for javascript errors and page performance.

I should consider not to include certain javascript references (f.e. collecting statistics with google analytics) when the page is executed for preview generation. Code example:

if(PageRenderer.RenderingReason == RenderingReason.ScreenshotGeneration) {
 ....
}

We will look into implementing #78 soon as well.

**Comment by napernik** [comment]
We added a new config setting "functionPreviewEnabled", which can be set to false on environments that do not support phantomjs properly (f.e. Windows Azure Websites)  https://github.com/Orckestra/C1-CMS/commit/cd817e634e4948a22eb22f61be5aab3061b7d7a6

**Comment by burningice2866** [comment]
+100

:)

**Comment by wwwysocki** [comment]
>We added a new config setting "functionPreviewEnabled", which can be set to false on environments that do not support phantomjs properly (f.e. Windows Azure Websites)

Verified on 20160420.1

Documentation: http://docs.composite.net/Function-Previews
