### ISSUE TITLE
Impossible to create the same item in another Culture

### ISSUE THREAD

**Issue by gretro** [Orckestra/C1-CMS#108]
My website has two languages: English and french.

Whenever I create a new page in English, it seems impossible a french version of the same page (I want them to have the same ID). Is there something I'm missing?

**Comment by burningice2866** [comment]
In the C1 Console, go to View > Translation... and make sure English is selected as the language to translate from.

When this is done, select French as language in the lower right corner and you will see a "Globe" icon in your Content-tree for each page that exists in English but not in French.

**Comment by DBailey635** [comment]
There's a whole section on creating multiple language websites at: [http://users.composite.net/Pages/MultipleLanguages](http://users.composite.net/Pages/MultipleLanguages) . It covers setting up multiple languages, switching between them and translating pages

**Comment by gretro** [comment]
@DBailey635 Ok, I got it. The flow to get there is not intuitive at all however.
