### ISSUE TITLE
[5.0 Bug] PDFs can't open in browser

### ISSUE THREAD

**Issue by bpprox22** [Orckestra/C1-CMS#109]
After a PDF has been added to the site, if you create a link to the PDF on a page, the default action when clicked is: it downloads. This happens whether the "Target" is set to open in a new window or not. Some of the sites we do, require PDFs to be viewed in the browser.

**Note**: In 4.3, if you add "?download=false" query string to the link's _href_ attribute through the source view in the Composite Console, the PDF will open in the browser. 

This is not the case with 5.0. If you add the "?download=false" query string to the _href_ attribute, Composite disregards it and creates the link as if there was no query string there. After the page loads, I can manually add it by inspecting the page and adding it to the attribute -- this is of course not going to help when creating the link. 

Although having to manually add "?download=false" to the _href_ is not the most elegant solution, it works fine in 4.3. I opened a question on StackOverflow with more details [here](http://stackoverflow.com/questions/34516059/open-pdf-in-browser-instead-of-downloading-it).

**Comment by wwwysocki** [comment]
**Summary**: A link to a media file loses the query string when used. This makes it impossible to use query strings like `?download=false`.

**Repro**:

1. Edit a page
2. Drag and drop a PDF file from Windows Explorer onto the page.
3. When prompted, select where to upload the file in the Media Archive.
4. On the page, switch to Source.
5. Change the query string that follows the media file's GUID in the `href` to `?download=false`.
6. Save and publish the page.
7. Open the page in a browser.
8. Hover over the link and check the generated link.
9. Click the link.


**Expected**:

* For Step 8: The link shows the query string `?download=false`.
* For Step 9: In browsers like Firefox or Chrome, the PDF file should **open** in the internal viewer.

**Actual**:

* For Step 8: The link has no query string `?download=false` at all.
* For Step 9: The browser normally prompts you to **save** the PDF file.

**Comment by wwwysocki** [comment]
For the time being, a kind of workaround might be this (although not a good one and not 100% working in all cases (browsers etc)).

1. System > / > Create a folder, for example, "Downloads".
2. Upload the PDF file (say, "Test.pdf") in there.
3. Edit a page.
4. Switch to Source.
5. Manually add a hyperlink and set its href attribute to the relative path to this file. Something like this:

`<a href="/Downloads/Test.pdf">View Test.pdf</a>`

**Comment by mawtex** [comment]
Fixed in dev

**Comment by wwwysocki** [comment]
Verified on 20160322.1

**Comment by blachawk** [comment]
This is still a problem for me.
