### ISSUE TITLE
Google Page Speed Insides in C1 Console - always c1mode(relative)

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#110]
Google Page Speed Insides in C1 Console always works in c1mode(relative) which leads to wrong results - instead of public page we receive /Composite/top.aspx analyze (which is NOT optimized properly, by the way). 
![capture](https://cloud.githubusercontent.com/assets/11037398/12790000/1b193e7c-ca55-11e5-8f07-c1e30729743f.PNG)

**Comment by wwwysocki** [comment]
How do you know that it is /Composite/top.aspx that gets analyzed?

When you run the analysis, the address bar clearly shows what page it is analyzing (see below)

Besides, some errors it finds on a page are also clearly related to that page, like non-compressed images, or not-minified CSSs etc (see below)

(As far as I understand, Composite C1 just embeds (in a frame?) a real page https://developers.google.com/speed/pagespeed/insights and passes the public URL to the current page, which you can see in the Google PageSpeed Insights address bar.)


![search](https://cloud.githubusercontent.com/assets/14821915/12973305/0f5d26e2-d0b4-11e5-9106-cc35d1561eec.png)



![getting-started](https://cloud.githubusercontent.com/assets/14821915/12973307/14f7664e-d0b4-11e5-823c-b3109f83abb8.png)


![blog](https://cloud.githubusercontent.com/assets/14821915/12973432/00a4889c-d0b5-11e5-9870-c7d5877dc603.png)
