### ISSUE TITLE
W3C Markup Validation and W3C Mobile OK in Console - broken

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#111]
W3C Markup Validation validation doesn't work, same as W3C Mobile OK

**Comment by wwwysocki** [comment]
Repro:

1. Select a page in the tree.
2. Click the **View Modes** button.
3. Click **W3C Markup Validation**, or **W3C Mobile OK**.
4. Check the browser view.

**Expected**:

* An external page loads and shows the results

**Actual**:

* A blank page shows


![w3c-and-mobile-validation](https://cloud.githubusercontent.com/assets/14821915/12973904/9d69c46e-d0b8-11e5-8d96-aa7dfced0ff3.png)

**Comment by mawtex** [comment]
As Taras indicate W3C usage broke (they send X-Frame-Options HTTP header preventing us from embedding their result in the C1 Console). Changed validation service from W3C to validator.nu and removed the mobile validation option.

**Comment by wwwysocki** [comment]
Verified on 20160316.1
