### ISSUE TITLE
TIF files can't be previewed or inserted as image files

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#114]
The issues might be related, so reported as 2-in-1

# 1

1. Upload a .tif image file in the Media perpsective.
2. Select it in the tree

**Expected**:
* Can be previewed as an image file

**Actual**:
* Can't be previewed

# 2

3. Content / Edit a page / Insert / Image
4. Look for the uploaded TIF file

**Expected**:
* Can be inserted as an image file

**Actual**:
* Can't be inserted

**Comment by mawtex** [comment]
See http://stackoverflow.com/questions/2176991/display-tiff-image-in-all-web-browser - TIFF is not a image format supported on web
