### ISSUE TITLE
Can't change the data access language for a user because no validation message shows up in Firefox, IE11, Edge

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#120]
**Browsers affected**: Firefox, IE11, Edge
(Chrome is OK).

**Repro**:

0. Use one of the affected browsers.
1. Make sure at least 2 languages added to the website (**System** / **Languages**)
2. Add a new user.
3. On the **Permissions** tab, for the **Data Access Language**, select a non-default language.
4. Unselect the default language.
5. Stay on the **Permissions** tab.
6. Click **Save**. At this point, the **General** tab should show a validation sign.
7. Switch to the **General** tab.

![data-access-language-issue](https://cloud.githubusercontent.com/assets/14821915/13103559/f1b167b0-d55f-11e5-90e3-6511ad1e9899.png)

**Expected**:

* A popup (or some other way) should show up and state the error.

**Actual**: 

1. The change hasn't been saved.
2. A validation sign appears on the **General** tab.
3. When you switch to the **General** tab, nothing indicates any error.

**Notes**:

1. In Chrome an error balloon appears at the "Active Content Language" field.
2. This doesn't happen in other browsers when you switch to the "General" tab.
3. If you stay on the "General" tab when saving, the error balloon does show up in the affected browsers. (This can be a kind of workaround.)
4. When you have a balloon popped up and switch to any tab other than the "General" tab, you get this issue: https://github.com/Orckestra/C1-CMS/issues/122

**Comment by neexite** [comment]
Can't reproduce

**Comment by wwwysocki** [comment]
I've updated the steps and the title. The issue is not blocking (changed to 'medium'): at least one browser is OK and there is a workaround.

**Comment by wwwysocki** [comment]
Verified on 20160331.1
