### ISSUE TITLE
MvcFunctions absorbs exceptions and code results.

### ISSUE THREAD

**Issue by gretro** [Orckestra/C1-CMS#130]
MvcFunctions seems to absorb all exceptions, no matter what.

This is a problem because on some pages, we have logic that should trigger a 404 on the whole page if we don't find an artifact. Instead, the page looks full of errors. This is not nice on an end user's perspective.

![image](https://cloud.githubusercontent.com/assets/5721630/13541653/9e1c76b6-e22b-11e5-91c3-ccfb3ce2dff9.png)

It would be great if Exceptions could bubble all the way up and make the page crash, or at least if exceptions of type `HttpResponseException` (or `HttpStatusCodeResult` results) could be handled and return the right status code.

**Comment by mawtex** [comment]
In v5 we introduced a way to turn this feature (or annoyance if your will) off. 

In ~/App_Data/Composite/Composite.config locate the element 

/configuration/Composite.Core.Configuration.Plugins.GlobalSettingsProviderConfiguration/GlobalSettingsProviderPlugins/add

and the the attribute "prettifyRenderFunctionExceptions" to "false"

**Comment by mawtex** [comment]
Reopening this. While the above comment is a working fix we should always bubble HttpException.

**Comment by wwwysocki** [comment]
Verified on 20160316.1
