### ISSUE TITLE
C1 Console bug: Users are not deleted

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#131]
Re-pro: Settings => Users => Add new user, specify custom folder. Delete user- you will notice that folder will stay. Empty. Without user. If you look at datatypes - u will see that user is not removed.

**Comment by mawtex** [comment]
Which data types are we talking about?

**Comment by wwwysocki** [comment]
The user gets correctly deleted from:

```
Composite.Data.Types.IUser.xml
Composite.Data.Types.IUserActiveLocale.xml
Composite.Data.Types.IUserSettings.xml
```

But remains undeleted from:

`Composite.Data.Types.IUserFormLogin.xml`

where it is referenced by Id.

(I guess we might have this issue reported in the TFS.)

**Comment by wwwysocki** [comment]
Verified on 20160315.1
