### ISSUE TITLE
Refreshing a node in a tree moves the focus one level up

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#135]
**Note**: It occurs practially on tree elements of all types and kinds (Data, Functions, Media, Packages etc) - except occasionally for pages. (Pages seem to be affected too)

**Repro**:

1. Media > Expand Media Archive > Expand a media folder.
2. Select an item (media file).
3. Click the Refresh button on the toolbar, or right-click the item and click "Refresh" on the context menu.

**Expected**: The selection (focus) stays on the item (media file).
**Actual**: The selection moves one level up to its parent element (the media folder).

As a result any preview in the browser view always changes on "Refresh".

**Comment by neexite** [comment]
https://github.com/Orckestra/C1-CMS/commit/b50d1e77bd92b7113857fbf576f96802aefec5a9

**Comment by wwwysocki** [comment]
Verified on 20160318.1
