### ISSUE TITLE
Can't add any page on Bare Bones

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#137]
1. Run the setup wizard.
2. Select the **Bare Bones** for your starter site.
3. Once logged in, in "Layout" add a page template and a page type.
4. In "Content", try and add a page.

**Expected**: A button "Add page" or the like is on the toolbar, or a menu item in the context menu.
**Actual**: No button, no menu item. It's impossible to add a home page.

![cant-add-pages](https://cloud.githubusercontent.com/assets/14821915/13668583/6589aae0-e6c6-11e5-9a95-5baf6ef52c91.png)

**Comment by DBailey635** [comment]
I don't think bare bones site includes a page type or page template, so you can't create a page until you have these items.

**Comment by wwwysocki** [comment]
Step 3

**Comment by DBailey635** [comment]
I'm not seeing the same thing as you. After adding the type and template, I got the button and the Add Website contextual menu item:

![screenshot](https://cloud.githubusercontent.com/assets/14888727/13673119/8bc343fc-e6cf-11e5-92c4-7eb155c461ab.png)

Am using v5.0 release.

**Comment by wwwysocki** [comment]
This is not the 5.0 release :) We are moving on

**Comment by DBailey635** [comment]
OK. Just loaded the dev fork and rebuilt. After adding types and templates, the content perspective does appear to refresh (it flashes), but the button and contextual menu don't appear now (maybe something has broken between v5.0 release and the latest build).

However, if you reload the entire console (F5 in browser), the button and contextual menu item does appear, so it's not a complete blocking issue.

**Comment by wwwysocki** [comment]
http://screencast-o-matic.com/watch/cDe6FE1b0O

**Comment by wwwysocki** [comment]
Verified
20160311.4
