### ISSUE TITLE
C1 Console usability: Language selector is not sorted alphabetically

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#140]
![image](https://cloud.githubusercontent.com/assets/11037398/13851077/f37b2510-ec19-11e5-811c-2ed219954a69.png)

See image. There is no logic how languages are sorted. Expecting - sort by culture name.

**Comment by wwwysocki** [comment]
**Repro**:

1. Have these website languages (locales) added: English (US), English (Canada), German, French (Canada).
2. Drop down the language switching menu in the C1 Console (top right).
3. Notice the order the items are sorted

**Expected**: The items are sorted alphabetically by language:

1. English (Canada)
2. English (US)
3. French (Canada)
4. German

**Actual**: The order seems random (or in a manner other than alphabetical):

1. German
2. English (US)
3. English (Canada)
4. French (Canada)

**Comment by wwwysocki** [comment]
Verified on 20160322.1
