### ISSUE TITLE
[MS Edge] The cursor gets into wating mode when uploading an image

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#144]
**Prerequisites**:

1. Use Microsoft Edge.
2. Use a fresh installation of Composite C1.

**Repro**:

1. Create a page.
2. Insert > Image.
3. In the "Select Image" window, choose to upload an image
4. Select a file > Finish.

**Expected**: You can now click "OK" in the "Select Image" window.
**Actual**: The cursor gets into waiting mode.

**Note**: Might be OK on used installations, or after you've uploaded a file successfully.

**Video**: http://screencast-o-matic.com/watch/cDerjk10dm

**Comment by mawtex** [comment]
@wwwysocki Looks like an issue for any session where media upload have not previously been done (via the media perspective), so the prerequisites step 2 could be "Make sure to reload the console in case you have uploaded any media in the current session".

**Comment by wwwysocki** [comment]
Fixed.

Verified on 20160331.1
