### ISSUE TITLE
Microdata in Visual Editor

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS#15]
When working with Microdata (https://schema.org/docs/gs.html) in the Visual Editor (source mode), many of the important tags are stripped when you want to save the page.

Ie. the following

```
<div itemscope="itemscope" itemtype="http://schema.org/EmailMessage">
  <div itemprop="potentialAction" itemscope="itemscope" itemtype="http://schema.org/ViewAction">
    <link itemprop="target" href="https://watch-movies.com/watch?movieId=abc123"/>
    <meta itemprop="name" content="Watch movie"/>
  </div>
  <meta itemprop="description" content="Watch the 'Avengers' movie online"/>
</div>
```

is stripped to 

```
<div itemscope="itemscope" itemtype="http://schema.org/EmailMessage">
  <div itemprop="potentialAction" itemscope="itemscope" itemtype="http://schema.org/ViewAction" />
</div>
```

**Comment by wwwysocki** [comment]
Logged as Issue 5234 in HQ TFS

**Comment by DBailey635** [comment]
Would this be a case where adding more items to TinyMCE's valid_elements init would help?

**Comment by mawtex** [comment]
As far as I can see from https://schema.org/docs/gs.html is is <link /> and <meta /> elements we should accept in the html body - if there are other elements I'm missing let me know. Attributes seem to work just fine (except you need to to the xhtml doubling itemscope="itemscope")
