### ISSUE TITLE
Enforced password history allows passwords still in history

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#163]
**Repro**:

1. Enforce the password history with `Composite.C1Console.Security.Plugins.PasswordPolicy/@passwordHistoryLength` set to "3", which means (3 old password + 1 current password) ([docs](http://docs.composite.net/Configuration/Password-Policy#EnforcePasswordHistory))
2. Have the password for the C1 Console user expired.
3. Use a new password 1 ('aaaaaa').
4. Step 2 + Use a new password 2 ('bbbbbb').
5. Step 2 + Use a new password 3 ('cccccc').
6. Step 2 + Use a new password 4 ('dddddd'). (At this point, the last 4 passwords are 3 old ones 'aaaaaa', 'bbbbbb', 'cccccc' and the current one 'dddddd')
7. Step 2 + Use the old password 1 ('aaaaaa').

**Expected**: The old password 1 ('aaaaaa') not accepted.
**Actual**: The old password (one of the three) accepted.

**Comment by mawtex** [comment]
Vitaly, did you restart the C1 site after step 1?

**Comment by wwwysocki** [comment]
> Vitaly, did you restart the C1 site after step 1?

I have an impression that I did. But I just retested it, also restarting it every time after Step 2 - and the issue is gone (20160331.1).
