### ISSUE TITLE
Editing and Saving Razor Function call cause markup duplication

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#169]
I don't have stable re-pro, but it's happens from time to time, rarely. I have reports from other team members.

Probably related to the functions with checkbox.

**Comment by napernik** [comment]
On which C1 version/browser is it reproducible? 

It is hard to address without a repro, next time you see the issue, please check the source markup of the page, it could be that it is reproducible only if the function is placed within certain html tags.

**Comment by mawtex** [comment]
Will close this - reopen if a repro come along
