### ISSUE TITLE
Tab or Whitespace?

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS#17]
@neexite seems to be changing whitespaces to tabs (https://github.com/Orckestra/C1-CMS/commit/9b5242556106170bfad1dab7ad759c726b4d5365) while @InnaBoitsun is changing tabs to whitespaces (https://github.com/Orckestra/C1-CMS/commit/67c28888bf21c63f93722e4ba3904131e0dd7877)

Would it be possible to settle on one or the other and then enforce it?

**Comment by mawtex** [comment]
Yeah, let's correct that.

**Comment by mawtex** [comment]
CSS, JS -  use Tabs
C# - use Spaces

**Comment by burningice2866** [comment]
This commit have turned the spaces in aspx/asmx files into tabs :( It is possible to configure tabs/spaces in Visual Studio independently based on the language of the file.

![image](https://cloud.githubusercontent.com/assets/333952/10904800/2a9c4394-8216-11e5-994b-69884888400c.png)

**Comment by InnaBoitsun** [comment]
@burningice2866 we decided to use next:
CSS, JS, HTML/ASPX, XML- tabs
С# - spaces

**Comment by napernik** [comment]
@burningice2866 It doesn't look like VS allows different formatting for aspx/ashx/asmx files, so we'll have to use tabs there as well.

**Comment by burningice2866** [comment]
@napernik if you wanted tabs only for js and css, it should be possble to set whitespace for 'All languages' and only override it with tabs for css and js.
