### ISSUE TITLE
Build error: Unable to start program. Composite.Workflows.dll is not a valid Win32 application

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#170]
I've just wiped my local copy of C1 and have downloaded a fresh copy of the dev build from GitHub, and got the following error upon build:

![screenshot](https://cloud.githubusercontent.com/assets/14888727/14313310/be4fb2b4-fbe8-11e5-8269-06fcd5c85569.jpg)

Any ideas?

**Comment by mawtex** [comment]
Right click the web project, set it as startup project and then launch again. I will keep this issue open, since we should ensure the web application is the default - you are not the first to ask this question ;)

**Comment by DBailey635** [comment]
Thanks. That worked... however, on first build in VS2015, it sent me to http://localhost/Home, which meant I got a 404 error. I had to remove the Home part of the URL to run through the setup process. It might be worth adding a redirect into the code, in case this happens for other people.

**Comment by mawtex** [comment]
The http://localhost/Home things sounds like your browser having been redirected from / to /Home at some earlier point on the same host name and this is now cached in your browser. If you flush your browser cache you should see this go away.

**Comment by napernik** [comment]
And now the "Website" project will be the startup one :) https://github.com/Orckestra/C1-CMS/commit/e4155409eb96f740e99da2f6361cf9f2ecf21fa0
