### ISSUE TITLE
An empty tab on a dynamic data form when a postback occurs on another tab

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#179]
**Repro**:

1. Download and install the package: [Composite.Test.EmptyTabs](https://dl.dropboxusercontent.com/u/11887629/Composite.Test.EmptyTabs.zip)
2. Data > Test.Company > Add Data
3. **Important!** Don't switch to the "Settings 2" tab yet
4. On the "Settings 1" tab, enter a value in the "Name" field.
4. Select an image file for the "Logo" field.
5. Switch to the "Settings 2" tab now.

**Expected**: The tab shows its fields ("Country" here)
**Actual**: The tab is blank (see below)

**Notes**:

* Tab 1 should have a field with a widget that **sends a postback** when set (ImageSelector here)
* Tab 2 should have a field with a **required selector** widget that, as a result, stays not set ('Selector' here)

![empty-tab](https://cloud.githubusercontent.com/assets/14821915/15608831/ff77a738-2424-11e6-8d6c-33eba7a9dcf6.png)

**Comment by gertsonderby** [comment]
Can replicate this. I get the following error from BindingFinder.js:
`Uncaught Could not resolve descendants of unattached binding [FieldBinding]`

**Comment by wwwysocki** [comment]
Fixed and verified in the "dev" (20160602.1)
