### ISSUE TITLE
Question: Why do I get "The target "GatherAllFilesToPublish" does not exist in the project" when publishing?

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#180]
I'm trying to build and publish the current "dev" branch of C1 to a file-system location, in order to try something out, but I keep getting the following error, and no files are saved:

`Error: The target "GatherAllFilesToPublish" does not exist in the project. WebSite C:\Users\baid1\Source\Repos\C1-CMS\Website\WebSite.csproj 0	`

Any ideas?  What's the best way to create a release, similar to the ones [here](https://github.com/Orckestra/C1-CMS/releases)?

**Comment by napernik** [comment]
The error you experience is related to one of the Visaul Studio build related files - Microsoft.WebApplication.targets. LIkely you have installed some component that broke it. 

http://stackoverflow.com/questions/10989051/why-do-i-get-the-error-the-target-gatherallfilestopublish-does-not-exist
