### ISSUE TITLE
A validation error on a page's Metadata tab not indicated when saving the page

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#184]
**Prerequisites**:

1. Download and install the package: [Composite.Test.PageMetaTab](https://dl.dropboxusercontent.com/u/11887629/Composite.Test.PageMetaTab.zip)
2. From the "Content" perspective, add a metafield - "SimpleMeta" - to a page
3. Make sure it's set to "Always inherit".

**Repro**:

1. Create a child page below the page you used in Step 2 above.
2. **Important!** Don't switch to the "Metadata" tab.
3. Make some change in the content to force the "Save" button to activate.
4. Click "Save" (as opposed to "Save & Publish").

**Expected**: An indication of a validation error on the "Metadata" tab. Compare to the behavior when you click "Save & Publish" instead. (It opens the Metadata tab and shows "Required" in the field that fails to validate.)

**Actual**: No indication of an error. The "Save" button gets inactive, the page's tab shows * (not saved)

**Comment by gertsonderby** [comment]
Fixing this was pretty simple, since it was caused by me missing that we have two separate save functions. So I consolidated them into one!

Fix is on branch `fix-tab-render`.

**Comment by wwwysocki** [comment]
verified on `fix-tab-render` (20160603.3)
