### ISSUE TITLE
too much error when building

### ISSUE THREAD

**Issue by a57571735** [Orckestra/C1-CMS#207]
![image](https://cloud.githubusercontent.com/assets/20694884/17584306/592566ea-5fe8-11e6-8a73-07f4626629dc.png)

**Comment by napernik** [comment]
Which version of VisualStudio are you using? The latest build requires VS 2015 which supports C# 6.0 syntax

**Comment by a57571735** [comment]
VisualStudio 2013 .net framework 4.5.1，c# 6.0 not support vs2013&win7，thanks
