### ISSUE TITLE
Visual Editor - Cut / Paste from right click menu on functions doesn't work

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#22]
How to reproduce: Open visual editor, click on function, right click - Cut, than Paste - nothing happens.
Workaround: use keyword - Ctrl + X to cut, Ctrl + V to paste.

**Comment by mawtex** [comment]
Taras, clipboard access from JavaScript is limited so I don't know if this is even fixable. If not, we should get rid of the context menu copy/paste options.

**Comment by neexite** [comment]
removed
