### ISSUE TITLE
Package Creator can't build packages with new SharpZipLib

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#29]
**Repro**:

1. Install the latest version of Composite.Tools.PackageCreator.
2. Create a simple package.
3. Try and download the package.

**Expected**: The package gets downloaded.
**Actual**: An error pops up

**Error**:

System.IO.FileLoadException: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.85.5.452, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference...

**Comment by burningice2866** [comment]
This can be fixed by adding a assemblyBinding redirect in web.config... should prop. be done by the PackageCreator package upon install

```
<runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="ICSharpCode.SharpZipLib" publicKeyToken="1b03e6acf1164f73" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-0.86.0.518" newVersion="0.86.0.518" />
    </dependentAssembly>
  </assemblyBinding>
</runtime>
```

**Comment by napernik** [comment]
I'm thinking of update PackageCreator, so it uses build in .net library classes for zip generation, to remove the dependency completely. In the core, it may have sense to reference the old version, or add a binding so we won't have any compatibility issues with existing solutions. And in future - to also remove the dependency as well.

**Comment by burningice2866** [comment]
@napernik should be enough to add the assemblyBinding in your out-of-the-box web.config... should resolve any any compatibility issues with existing solutions

**Comment by wwwysocki** [comment]
Verified with:
* C1: 5.0.5795.21979
* Package: 3.6.3
