### ISSUE TITLE
Feature Request: For all Datatypes, modify field types dropdown to allow insertion of a valid C1 UserId

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#30]
We would like to be able to allocate certain areas in our website to specified individuals. For example; the HR section of our website would be owned by the Head of HR, but certain pages within that section would have different individuals responsible for them.  This is in addition to the permission settings for a section (we want to track page owners, not those who can edit pages).

If a page in the HR section hasn't been modified for a certain length of time, a weekly email would be generated that would be sent to both the section owner and the page owner. They would then check and modify the page to stop receiving these emails.

To handle this, I have created a PageMetatype with two Datatype fields: SectionOwner and PageOwner. These fields inherit from the level above. At the moment, I'm storing the data in these fields as strings, but it would be useful if we could add raw valid C1 UserIds here instead.

What I'd like to propose is, that alongside DataReference as a field type, there is a new type for UserReference. When used, it would present a select field to the page editor, from which they could choose a valid user from a list of all global C1 UserIds.

An alternative possibility is that the DataReference type has a "C1 Users" option added, that does the same thing.

With this in place, the back-end process that generates reminder emails would be able to join this field value to the main C1 UserId list to find their email address, and send out the messages.

**Comment by DBailey635** [comment]
An alternative possibility is that the DataReference type has a "C1 Users" option added.

**Comment by mawtex** [comment]
This is a bit tricky to accommodate since the list C1 Users are not always maintained as a C1 Data type - we do ship with a data type IUser which is used to host logins by default, but we can't hard wire this into the data system. 

But you can still achieve what you are looking for.

Edit the form markup and replace the textbox

      <TextBox Label="LABEL_HERE" Help="" SpellCheck="true">
        <TextBox.Text>
          <cms:bind source="FIELD_NAME_HERE" />
        </TextBox.Text>
      </TextBox>

with this

      <KeySelector Label="LABEL_HERE" Help="" OptionsKeyField="Key" OptionsLabelField="Label" Required="true">
        <KeySelector.Selected>
          <cms:bind source="FIELD_NAME_HERE" />
        </KeySelector.Selected>
        <KeySelector.Options>
          <ff:StaticMethodCall Type="&lt;t n=&quot;Composite.Plugins.Functions.WidgetFunctionProviders.StandardWidgetFunctionProvider.DataReference.DataReferenceSelectorWidgetFunction`1&quot;&gt;&#xD;&#xA;  &lt;t n=&quot;Composite.Data.Types.IUser&quot; /&gt;&#xD;&#xA;&lt;/t&gt;" Method="GetOptions" Parameters="Composite.Data.Types.IUser" />
        </KeySelector.Options>
      </KeySelector>

**Comment by DBailey635** [comment]
Thanks Marcus. That's really useful.

**Comment by burningice2866** [comment]
To make it more robust, the 

```
<ff:StaticMethodCall Type="&lt;t n=&quot;Composite.Plugins.Functions.WidgetFunctionProviders.StandardWidgetFunctionProvider.DataReference.DataReferenceSelectorWidgetFunction`1&quot;&gt;&#xD;&#xA;  &lt;t n=&quot;Composite.Data.Types.IUser&quot; /&gt;&#xD;&#xA;&lt;/t&gt;" Method="GetOptions" Parameters="Composite.Data.Types.IUser" />
```

should be replaced to a call to a custom method that returns id's based on the UserFacade - thus in turn returning users from custom providers as well. Like this

```
<ff:StaticMethodCall Type="ConsoleHelpers" Method="GetAllUserIds" />
```
