### ISSUE TITLE
Razor and other syntax no more highlighted in the Source Editor

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#31]
**Repro:**

1. Open / create a Razor function in the C1 Console
2. Check the code in the editor

**Expected:** Highlighted accordingly
**Actual:** Not highlighted at all

**Note:** Apart from Razor, .NET (C#) syntax doesn't seem highlighted, either (aspx, ashx, cs, asax)

**Comment by neexite** [comment]
no file Website/Composite/lib/codemirror/mode/razor/razor.js in build

**Comment by wwwysocki** [comment]
Please see the note to the repro steps, 
or edit the following file types in the System perspective
* asax
* aspx
* ashx
