### ISSUE TITLE
Tag previous releases

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS#36]
Would it be possible to go through the repo and add release tags to the previous versions, at least all of the 4.x releases?

I've done it here https://github.com/burningice2866/C1-CMS/releases, its just a matter of matching the releases on https://compositec1.codeplex.com/releases/view/612595 with the corresponding commits :)

**Comment by DBailey635** [comment]
That's a great idea. It would allow developers to compare changes for each version released.

**Comment by napernik** [comment]
Done. Down to v2.0, without some minor old updates/patches
