### ISSUE TITLE
Inner HTML is pasted instead of the function itself when the function is copied/pasted

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#42]
**Repro**:

(In Chrome, IE, MS Edge. Not in Firefox)

1. Use the Venus starter site.
2. Edit the home page.
3. Cut the first function on the page (Ctrl+C).
4. Paste it somewhere on the page (Ctrl+P).

**Expected**: The copy of the function is pasted.
**Actual**: Only the content of its XhtmlDocument parameter is pasted (inner HTML not the function)

![cut-paste-c1-functions-with-xhtml-document-parameters](https://cloud.githubusercontent.com/assets/14821915/11336443/054dbf9a-91ee-11e5-8e85-739be664a820.png)

**Comment by neexite** [comment]
Other reproduce (Not C1)
Use WYSWYG editor(TinyMCE, CKEditor...)
1. Set attribute 'alt' for image  using UI: "<html> <head></head> <body> <h1 class="page-header">Welcome to Venus</h1> </body> </html>"
2. Copy the image (Ctrl+C).
3. Paste it somewhere in the editor (Ctrl+P).

Expected: The copy of the image is pasted.
Actual: Only the "Welcome to Venus" is pasted

**Comment by neexite** [comment]
One yet
>			<embed>
>				<html>
>					<head>
>					</head>
>					<body>
>						<h1 class="page-header">Welcome to Venus</h1>
>					</body>
>				</html>
>			</embed>

**Comment by neexite** [comment]
Fixed for C1
Reported to TinyMCE https://github.com/tinymce/tinymce/issues/2487
