### ISSUE TITLE
DecimalPrecisionValidator issues

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#5]
If static datatype have Decimal, like 3,2 (NNN.NN) DecimalPrecisionValidator doesnt work properly.

by setting attribute [DecimalPrecisionValidator(2,3)] I would expect it's validate scale and precision, but it's not. Static datatype generator tool generates this datatype value with precision validator only:

[DecimalPrecisionValidator(2)]  AND LazyFunctionProviedProperty (mistyping here Provied > Provided?) which works fine for precision, shoving obsolete warning that scale and precision required. When we use them - no validation works.

Mistyping error: C:\development\CompositeC1\C1-CMS\Composite\Data\Validation\Validators\DecimalPrecisionValidator.cs  - line 30 "valudation" > "validation"

**Comment by mawtex** [comment]
Not a bug -  [DecimalPrecisionValidator(2,3)]  in invalid :

        /// <param name="precision">Digits in total</param>
        /// <param name="scale">Digits after decimal point</param>

Try using  [DecimalPrecisionValidator(5,3)]  - allowing for 5 digits in total, 3 of those after the decimal point.

I will add a check on the DecimalPrecisionValidatorAttribute constructor so you will get an error if precision is less than scale.
