### ISSUE TITLE
No text wrap in the "Paste as Text" window

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#54]
**Repro:**

1. Edit a page.
2. Copy some multi-line paragraph (you can use the sample text below).
3. Paste > As Simple Text
4. Paste the text in the text area.

**Expected:** The text wraps and fills the text area in multiple lines.
**Actual:** The text doesn't wrap, and pasted as a single line.

**Note:** The issue also occurs on versions earlier than 5 

![image](https://cloud.githubusercontent.com/assets/14821915/11529101/7834826c-98f3-11e5-9fa1-160bf8083422.png)

**Sample text:**

The apple tree (Malus domestica) is a deciduous tree in the rose family best known for its sweet, pomaceous fruit, the apple. It is cultivated worldwide as a fruit tree, and is the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found today. Apples have been grown for thousands of years in Asia and Europe, and were brought to North America by European colonists. Apples have religious and mythological significance in many cultures, including Norse, Greek and European Christian traditions.

**Comment by neexite** [comment]
By design
