### ISSUE TITLE
Content tree is too wide

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#6]
When you open Composite C1 5.0, and expand Blog, than any of it's items - you will have horizontal scrolling. I understood you are targeting tablet / mobile users, but despite "compact" mode 4.3 allows you to see more children in the tree. You can clearly see same effect in Media tab. IMHO some padding / margin adjustment required in the tree - now it's too wide = waste of screen space.

![capture](https://cloud.githubusercontent.com/assets/11037398/10655368/db855378-7828-11e5-802d-70fb1332a5eb.PNG)

**Comment by mawtex** [comment]
So Inna's change 7d66bbb reduce the padding to a bare minimum, but in a situation like the sample image above the long file names are still not fully readable. What we may do is have the tree pane expand when a label overflows (eating up some of the space used by the browser view - with some sanity level, like 50% of the total width).

**Comment by aeont** [comment]
@mawtex tested and I see no difference.. look at screenshot - in 4.3 I can expand up to 5-6 levels VS 2-3 in 5.0. I.e. icons are too big, a lot of space is wasted. Again - didn't tested yet in mobile, probably make sense, but still, imho  too much space wasted. 

Tree icons is not best - wasting space and not properly describing "state". Simply look at Visual Studio 
![capture1](https://cloud.githubusercontent.com/assets/11037398/10681314/dd1520c4-78dc-11e5-8a4d-26bb876e4928.PNG)

how they show "opened" and closed and what is the width between the levels - they almost one on top other and C1 5.0 about twice big.

![capture](https://cloud.githubusercontent.com/assets/11037398/10681194/a678001e-78db-11e5-81a1-68ddb63af615.PNG)

**Comment by aeont** [comment]
..looking at Explorer in windows - even more compact and "nice to look at, looks "natural".

**Comment by InnaBoitsun** [comment]
You wrote, that see no difference, but compare next image BEFORE and AFTER change: 
![image](https://cloud.githubusercontent.com/assets/6649972/10687794/884791a2-7978-11e5-87a6-16c2d7b417a8.png)

**Comment by burningice2866** [comment]
I'm with @aeont here, icons and spacing is generally too big and, well, spacey.

Maybe consider making the styles for the console responsive, so you only use the large icons, padding and margins on smaller screens?

**Comment by DBailey635** [comment]
There's a lot to be said for big and spacey, particularly if you're using a touch screen device to edit your website. We have to deal with chubby fingers and Inna's slightly more compact spacing still works well for touch.

That being said, is there a need to keep the triangle > icons next to folders and pages containing sub-content?  Is there another way to denote items inside a branch that would be less bulky?
