### ISSUE TITLE
Syntax not highlighted in SQL functions

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#63]
1. Functions > Create an SQL function.
2. Check the SQL syntax on the "SQL Command" tab.

**Expected:** The syntax highlighted.
**Actual:** The syntax is not highlighted.

**Comment by wwwysocki** [comment]
Still active in the latest build

![sql-syntax-not-highlighted](https://cloud.githubusercontent.com/assets/14821915/11651343/c5c7e9de-9d98-11e5-8e76-32acc1a3780c.png)

**Comment by neexite** [comment]
Missing file \Composite\lib\codemirror\mode\sql\sql.js in build

**Comment by wwwysocki** [comment]
Verified on 20151214.1
