### ISSUE TITLE
Malformed short URL crash page generation

### ISSUE THREAD

**Issue by mawtex** [Orckestra/C1-CMS#65]
Repro:

1) Edit a page, highlight word, invoke "link to"
2) Select a page to link to and then edit the link text (double click link title)
3) Append &malformedQuery=true
4) Click OK and save page
5) View / preview page

Expected: The page will render. The malformed URL would be the page URL appended with the malformed query string.

Actual: Page generation crash.

Suggestion: Catch exceptions at a "per link" level so malformed URLs can never crash an entire page.

**Comment by wwwysocki** [comment]
Verified on 20151215.2
