### ISSUE TITLE
After following link from C1 Page Speed report, my functions perspective is empty.

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#70]
In content perspective, I browsed to a page and from the eye menu chose C1 Page Speed report.  Once on screen, I clicked a link to an individual function:

![c1-b2a](https://cloud.githubusercontent.com/assets/14888727/11661431/ca958e22-9dc9-11e5-98f0-815f5bffe4cf.jpg)

The console reset and when it returned it tried to load the function perspective... however, this was now empty:

![c1-b2b](https://cloud.githubusercontent.com/assets/14888727/11661453/e5e5f7e8-9dc9-11e5-80e6-def94d8b4de1.jpg)

Attempts to reload the perspective continue to show this empty.

I'm using d0a913c95d91f54e233b9066d4d1c903aaf9627c 

After restarting server, this issue resolved itself.

**Comment by wwwysocki** [comment]
There was an issue like this in some pre-v5 betas. It was then fixed.

Please reopen if you are still experiencing the issue in Version 5.0 or later.
