### ISSUE TITLE
Tabs with error icons on them create spaces below other tabs

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#71]
If you do not complete all required fields in a function and try to save it, the tab with the missing/incomplete/incorrect field is highlighted with a hand icon.  However, this hand icon is larger than the tab height and so pushes down on the containing block, creating spaces below other tabs:

![c1-b3](https://cloud.githubusercontent.com/assets/14888727/11661952/3f84a630-9dcc-11e5-9ffd-63af76a44304.jpg)

You may need to resize the hand icon, or set a larger min-height value for tabs.

**Comment by DBailey635** [comment]
Hi @InnaBoitsun , Sorry... I should have noted that this applies only to sub-tabs, not the main tabs. The glitch appears to still be present in latest ef99a6b7e9c85ca9b5c571eb073baeba1e2db136 commit.

**Comment by InnaBoitsun** [comment]
@DBailey635 could you please let me know how to reproduce the issue?

**Comment by DBailey635** [comment]
@InnaBoitsun , Sure.

Easiest way to see this is to go to functions perspective and choose a function to experiment with (I used Composite.Xml.LoadFile). Don't enter a required parameter value and instead click the Results sub-tab. The Functions sub-tab is now flagged with the hand icon and the other tabs are now no longer connected the line below.

**Comment by InnaBoitsun** [comment]
@DBailey635 , yes and it should be fixed in changeset https://github.com/Orckestra/C1-CMS/commit/154fec53985b8f38749ed9286fd30b2c8b7cf2b8

**Comment by DBailey635** [comment]
OK. Thanks for checking @InnaBoitsun . It looks like my local copy of the project wasn't correctly syncing with GitHub. I've just deleted my local version and re-cloned it, and the issue no longer presents.
