### ISSUE TITLE
[PackageCreator] Package Creator crashes on DataType Items

### ISSUE THREAD

**Issue by gretro** [Orckestra/C1-CMS#73]
Using the Package Creator, I've came across a bug.

Whenever we want to add a DataType item to a package, it crashes. This is due to the fact that the Package Creator allows the same DataType to be added multiple times.

Every other item types are double-checked to make sure they aren't added as duplicates in the package, but not the DataType. This causes the Console to display an hourglass and freeze when we add the DataType or when we open the **Datetype items** node in the Package Creator.

**Comment by burningice2866** [comment]
@gretro Can you create this issue here as well, maybe it will get more attention there https://github.com/Orckestra/C1-Packages/issues

**Comment by neexite** [comment]
https://github.com/Orckestra/C1-Packages/commit/4be4e442c8a8bb90479f90f8cba581118785275c

**Comment by gretro** [comment]
Cool. Thanks.

When will this be available in the Package Manager on C1?

**Comment by wwwysocki** [comment]
Version 3.6.4
Tested on Composite C1 5.0
Published on the package server

**Comment by gretro** [comment]
Thanks!
