### ISSUE TITLE
C1 Console OpenView for a view that is already open, does not bring focus to it

### ISSUE THREAD

**Issue by mawtex** [Orckestra/C1-CMS#74]
Repro:

1) In the C1 Console, Focus the "Websites" node
2) Click "List Unpublished Pages" ("Unpublished" view opens in new tab)
3) Go back to the Content Browser
4) Click "List Unpublished Pages"

Expected: the tab containing the "Unpublished" view (already open) is focused
Actual: Nothing (the existing view is also unaffected, not reloaded).

**Comment by wwwysocki** [comment]
Verified on 20151217.1
The current behavior is:
1. The opened "Unpublished" tab gets selected (green characters) when the "Websites" node is selected.
2. Step 4 from the repro above > The tab gets activated/focused on
