### ISSUE TITLE
Feature Request: In the "List Unpublished Pages" report, clicking a page should open that page for editing or review.

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#75]
In the "List Unpublished Pages" report, clicking a page should open that page for editing or highlight it in the website tree for review.

**Comment by DBailey635** [comment]
It would also be nice if the report could be filtered to only show items that you have permission to approve or publish.

**Comment by burningice2866** [comment]
Making the "List unpblished pages" page better is interestingly enough one of the oldest and top-voted feature request on codeplex as well :) http://compositec1.codeplex.com/workitem/531

**Comment by DBailey635** [comment]
Last night I put together some screen-shots of how this could work.

When launching the "List Unpublished Pages" report, it opens as currently in a new tab. Inside, there are now five sub-tabs:

**Overview**

![overview](https://cloud.githubusercontent.com/assets/14888727/12143397/41567aca-b478-11e5-8555-f873133cf5cd.png)

This overview lists the number of pending drafts, approval requests and publish requests, both in total, and for the individual viewing it.

**Pages You are Editing**

![pages-you-are-editing](https://cloud.githubusercontent.com/assets/14888727/12143398/448482e6-b478-11e5-82ad-88abe586765a.png)

**Pages You Can Approve**

![pages-you-can-approve](https://cloud.githubusercontent.com/assets/14888727/12143406/4f32fcd6-b478-11e5-84e7-57c58fc3b0a9.png)

This list is filtered to only show the user the pages or data items they have explicit permissions to approve. Other pages are excluded.

**Pages You Can Publish**

![pages-you-can-publish](https://cloud.githubusercontent.com/assets/14888727/12143412/56ee4fde-b478-11e5-8494-db222ed09b90.png)

This list is filtered to only show the user the pages or data items they have explicit permissions to publish. Other pages are excluded.

**All Unpublished Pages**

![all-unpublished](https://cloud.githubusercontent.com/assets/14888727/12143417/5b8e35fe-b478-11e5-82b3-f362386ec7e7.png)

This is the old tree view from the current system, only with clickable icons that take you to the preview of the page.

Let me know what you think...

**Comment by DBailey635** [comment]
Given the recent changes to the "List Unpublished Pages" report and the introduction of the Bulk Publishing feature, I'm going to close this enhancement request, as it implements most of what I was asking for.

I still think that there should be an personalised overview page, a users column in the list, and that the list should have filters, but I'll log these as new issues.
