### ISSUE TITLE
Urgent: Starter Site disappeared

### ISSUE THREAD

**Issue by hyrmedia** [Orckestra/C1-CMS#80]
I installed Composite C1 5 locally, after cloning the repo from GitHub and building the project. The installation asked me to select a starter site, and selected the "Venus" site. I clicked around the newly installed Venus site a bit. Then I logged in to the admin backend, to get a feel for the interface and the product's capabilities; I started by examining the pages/components of the Venus website instance, under the "Websites" node. Everything looked good.

Then I browsed around the other areas of the admin backend -- including Data, Layout, and Settings. Finally I clicked back on the Content menu on the admin area sidebar. Now everything under the "Websites" node was missing!

I tried browsing to the front page directly, and the page just says "Site under construction - start here." The "start here" link just sends me to the admin backend.

Where did the starter site and all its content go??

**Comment by hyrmedia** [comment]
I may have an idea of what happened, actually. It occurs to me that I did have to remove the original default language via the System menu > Languages. This probably deleted the website content associated with the language.

**Is there some way to re-install the default website content, without having to completely reinstall the whole CMS?**

**Comment by aeont** [comment]
@hyrmedia 
1) make backup
2) download https://github.com/Orckestra/C1-Packages, download https://github.com/Orckestra/C1-Packages/blob/master/Composite.StarterSite.CorporateSite.Core/Composite.StarterSite.CorporateSite.Core/Release/Composite.StarterSite.CorporateSite.Core.zip
3) install this package. 

you might need play with install.xml inside Composite.StarterSite.CorporateSite.Core.zip to remove stuff you don;t need.

**Comment by InnaBoitsun** [comment]
Make sure to have a site backup before actions like that. 
We will improve "Language Delete" confirmation message and add more information that the all content(pages, localized data items) associated with that language will be deleted also.
