### ISSUE TITLE
No visual indication when TABbing the fields

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#81]
**Repro**:

1. Add or edit a data item with multiple fields.
2. Press TAB several times to move from filed to field.

**Expected**: You can tell what field is currently focused on.
**Actual**: No indication of what field is focused on at the moment.

**Comment by DBailey635** [comment]
Please let me know if the above commit works to fix this issue.

**Comment by wwwysocki** [comment]
Tested on 20160120.1
