### ISSUE TITLE
TreeDefinitions - Filters level limitation

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#89]
When I have few levels in my tree:

Level1
 Level2
  Level3
   Level4
    Level5

and at Level3 I want add new item - Level4, my Level2Id and Level3Id values will be pre-defined, as expected (because filters set), but Level1Id is not.

**Comment by mawtex** [comment]
Can you provide an example that demonstrate the problem (a repro)?

**Comment by aeont** [comment]
@mawtex it was my mistake, sorry. please close.
