### ISSUE TITLE
v5 Beta 1 main content browser page source button opening multiple identical tabs

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#9]
On content perspective, when browsing the website, there is a "page source" button to the right of the location bar, which when clicked repeatedly opens multiple identical source code tabs at the bottom of the console window. I'm not sure if this is intended, but I believe this should just toggle open and closed one tab (like the SEO assistant button).

![screenshot](https://cloud.githubusercontent.com/assets/14888727/10727556/a30d7f7c-7bd2-11e5-953a-8f05422092d0.png)

**Comment by mawtex** [comment]
I'm considering if we should kill of this button all together and make the HTML view it a "view" (activated via the eye). Having the HTML markup in its own dock is not really doing a lot for anyone.

Such a change would make us loose the ability to have multiple HTML sources side by side (or rather, in multiple tabs), but this is not a use case I expect many people to ever want.

**Comment by DBailey635** [comment]
I was a bit puzzled by it's inclusion here, as the tab appears to show the same HTML code that a normal browser user would see if they did a view source from the live website. I think that seeing the HTML of a pending (unpublished) page may be helpful in some circumstances, so putting it under the eye menu would be a good compromise (hide it away, but still give people the option to see it).

**Comment by mawtex** [comment]
Fixed - the dedicated "View source" button (which wold open new tabs with sources) is gone. Viewing source is now a "View" option which toggle like other view options. Change introduced in commit e7466147b6d9a7c68f8926a38c0a463d8e79dfaa
