### ISSUE TITLE
Static DataType with 2 KeyPropertyName's

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#92]
If we have datatype with:

[KeyPropertyName(0, "UserId")]
[KeyPropertyName(1, "CompanyId")]

.. add this fields as ForeignKey as well..

We cannot add data to this datatype with admin interface, because DynamicTypeForm overwrites UserId assigning random Guid each time..

**Comment by burningice2866** [comment]
I never had any luck either with using multiple key properties without having to make my own Workflows for handling the data.

If you inherit from the Basic1Step* classes in CompositeC1ContribCore (https://bitbucket.org/burningice/compositec1contrib/src/c822c4e7730e8044f73bb877cbc76183a7376e43/Core/Workflows/?at=default) its a matter of a few lines to create custom add/edit/delete workflows.

**Comment by mawtex** [comment]
Seems well answered by @burningice2866

**Comment by aeont** [comment]
@burningice2866 thank you.
@mawtex would it be fixed in C1?
