### ISSUE TITLE
"ReferenceError: PathBinding is not defined" error after login. Console doesn't load.

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#93]
After logging into latest build, I got an error of "ReferenceError: PathBinding is not defined" while Initializing Composite C1 console. The progress bar stalls and the console doesn't load.

**Comment by neexite** [comment]
Did you run *build* task on "Task Runner Explorer" after getting latest source?

**Comment by DBailey635** [comment]
Ah! That'll be it!

It's working now. Thanks @neexite.
