### ISSUE TITLE
.NET Framework 4.5 and dataannotations

### ISSUE THREAD

**Issue by sgedda** [Orckestra/C1-CMS#94]
I cannot upgrade from 4.0 to 4.5 after downloaded and opened C1 5.0. Is this possible? I would like to use dataannotations, for example Reqiured attribute and tried to reference  System.ComponentModel.DataAnnotations without any luck. (The website is already referencing the assembly) and cannot use the attributes that I would like.

**Comment by gretro** [comment]
I currently work on a project using C1 and we use 4.5.2 for all of our projects without an issue. How did you structure your project? Do you make modifications directly to the website or do you develop using an external project with publishes to the bin folder of the C1 Website hosted in IIS? We use the latter and it's been working very well for us.

**Comment by sgedda** [comment]
Hi again. Sorry for late reply. I am not using the entire source code, I downloaded the website through; https://github.com/Orckestra/C1-CMS/releases/download/v5.0/Composite.C1.5.0.zip. which targets .Net 4.0 and I didnt manage to upgrade ot 4.5 in visual studio 2013. How would I do this properly?

**Comment by napernik** [comment]
Hi @sgedda 
It looks like the solution file that is used in this download targets an old Visual Studio 2010, we will look into updating it. 

As for the .net version requirements 

C1 v4.1  requires .NET 4.5 
C1 5.0 requires .NET 4.5.1. 
The next version will require .NET 4.5.2.

**Comment by napernik** [comment]
You can open in in VS2015, and, in the property pages of the website project, change the target framework to .NET 4.5.1

![changetargetframework](https://cloud.githubusercontent.com/assets/1391705/14311312/ed6c40aa-fbe6-11e5-92f9-29654d8a30f3.png)
