### ISSUE TITLE
Bug: Multiple parameter types simultaneously ticked in functions, and input parameter option not selectable.

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#95]
I have a global datatype called "Demo" defined with three fields (in addition to the Id). After adding some data, I then went to the functions perspective and created a new XSLT function. On the "Function Calls" tab, I added the automatically generated GetDemoDataXml function. For all parameters in this function, multiple parameter types were simultaneously ticked.

![screenshot](https://cloud.githubusercontent.com/assets/14888727/12140330/f587ed9a-b45e-11e5-8eca-6abfb82776a3.jpg)

Switching between items un-ticked the chosen parameter type. The "Input Parameter" type was not selectable in any parameter. This makes building function next to impossible, unless you edit them in source mode.

Additionally, clicking the Source mode button, then reverting to Design mode, removed the icon from the Source mode button... leaving an empty box.

This bug is present in both v5.0 release and the latest build.

**Comment by wwwysocki** [comment]
Regarding 

> Additionally, clicking the Source mode button, then reverting to Design mode, removed the icon from the Source mode button... leaving an empty box.

I've created an issue https://github.com/Orckestra/C1-CMS/issues/117

**Comment by wwwysocki** [comment]
Regarding

> The "Input Parameter" type was not selectable in any parameter. 

The Input Parameter type is only available if :

1. You created an input parameter for the function - on the Input Parameter tab
2. An the input parameter's type matches that of the parameter of the called function. (For some parameters in function calls, only the Function type is available, like Filter on the `Get<DataType>` functions.

![input-parameter-added](https://cloud.githubusercontent.com/assets/14821915/12948679/40dbe10c-d00c-11e5-92ac-0b5bff12e2c1.png)

![input-parameter-used](https://cloud.githubusercontent.com/assets/14821915/12948682/45bf6fd6-d00c-11e5-8a0b-dd88222a8325.png)

Please see also http://docs.composite.net/Functions/XSLT/GuideToXsltFunctions/Creating-Input-Parameters

**Comment by wwwysocki** [comment]
Regarding

> For all parameters in this function, multiple parameter types were simultaneously ticked.

The "ticked" parameter types show which you cannot use for this very parameter,
while "un-ticked" are clickable and you can use them for you parameter.

In your case, the Filter parameter of a `Get<DataType>Xml` function always requires that it should be set via a function, namely, a function that filters entries.

However, I see the request for enhancement here - so I've taken the liberty to piggyback on your issue and create a new separate one https://github.com/Orckestra/C1-CMS/issues/118

So I'll close this one as being address. Please reopen if something is missed or not yet addressed.

**Comment by DBailey635** [comment]
Thanks @wwwysocki. Sorry I wasn't clear with my initial report.
